### ISSUE TITLE
Display Toast Time

### ISSUE THREAD

**Issue by mihaimyh** [Blazored/Toast#10]
Is  `options.Timeout` supposed to control how many seconds a toast should be displayed in the browser before it is going away?

If so, I put  options.Timeout = 20 but the toast is still dissapearing to fast?

Can we control the time a toast is displayed?

**Comment by chrissainty** [comment]
Thanks for reporting this. That option should control the time the toast is displayed. 

Could you let me know if you are using client-side Blazor or server-side Blazor?

**Comment by mihaimyh** [comment]
I am using Blazor with Client, Server and Shared Library.

The Toast is implemented on the client project.

**Comment by chrissainty** [comment]
@mihaimyh - I've just been testing this out but I can't seem to replicate the problem. I'm in the process of upgrading the package to .NET Core 3 preview 4. I would suggest you give it ago after the upgrade and see if you're still seeing the issue.
