### ISSUE TITLE
Toast with low z-index

### ISSUE THREAD

**Issue by drma-dev** [Blazored/Toast#101]
I'm using a bootstrap feature in which the button is with z-index 2, there is overlaying the toast.

![image](https://user-images.githubusercontent.com/12803050/103553702-9826ce00-4e8c-11eb-958d-b3fb80c1ad65.png)

**Comment by chrissainty** [comment]
You will need to override the `.blazored-toast-container` class in your CSS and provide a higher z-index.

**Comment by drma-dev** [comment]
@chrissainty 
but isn't 1 too low for a floating popup?

**Comment by chrissainty** [comment]
It depends, if nothing has a higher z-index then no. The problem with z-index is that there is always something which has a conflict for someone, somewhere. If we set it to 999 there will be something which has an index of 1000. It's a trivial task to set the z-index in a project.
