### ISSUE TITLE
[Feature Request] Is there any way to clear all toasts, or certain toasts?

### ISSUE THREAD

**Issue by szalapski** [Blazored/Toast#103]
**Is your feature request related to a problem? Please describe.**
I have a form that can give errors when the user tries to save. When unexpected errors occur, the errors are shown in a 30-second toast (as well as on the page, usually).  If the user corrects the errors and saves successfully, the error toasts are still shown till the 30 seconds are up, even though they no longer apply.

**Describe the solution you'd like**
I'd like to be able to clear all toasts early.  Perhaps `toastService.ClearAll();`, `toastService.ClearWarnings()`, etc...  I'd imagine fine-grained control might be covered by https://github.com/Blazored/Toast/issues/97 .

**Describe alternatives you've considered**
None come to mind.

**Comment by setezerocinco** [comment]
Any news about this functionality?

**Comment by chrissainty** [comment]
An update for toast will be coming next after an update to Typeahead. This will be addressed then unless someone wants to contribute a PR.
