### ISSUE TITLE
[Feature Request] OnToastClick custom behaviour

### ISSUE THREAD

**Issue by Mijalski** [Blazored/Toast#105]
Add a way to execute custom behaviour when an user clicks toast (not exit button).

Example:
When toast indicates to user that his download is ready, after click we would like to redirect him to a new page.

**Comment by chrissainty** [comment]
Hi @Mijalski, this seems a great addition, and thank you for providing a PR as well. Everything looks good so I'll get it merged and this will go out with the next release.
