### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by cryo75** [Blazored/Toast#108]
I placed the component in my main layout (above all other components). My layout is based on a header, left navigation menu and content components. 

The toast is being displayed above the content but below the header. How can I make it display above all other components? How can I access the z-order?

**Comment by chrissainty** [comment]
Can you provide a minimal repro of the issue. Once that is done I can offer some advice and we can get this resolved.

**Comment by jbarrineau06** [comment]
You just need to adjust the z-index on the class "blazored-toast-container". At least that's what I did.

**Comment by cryo75** [comment]
It worked
