### ISSUE TITLE
Toast message does not show,When calling from a service.

### ISSUE THREAD

**Issue by iAmBipinPaul** [Blazored/Toast#12]
Service class 
```csharp
   public class ServiceA
    {
        private readonly IToastService _toastService;

        public ServiceA(IToastService toastService)
        {
            _toastService = toastService;
        }
        public void showMessage()
        {
            _toastService.ShowSuccess("I'm a SUCCESS message with a custom title", "Congratulations!");
        }
    }
```
Startup
```csharp
  services.AddBlazoredToast(options => {
                options.Timeout = 5;
                options.Position = ToastPosition.BottomRight;
            });
            services.AddSingleton<ServiceA>();
```
Index.razor
```razor
@page "/"
@inject ServiceA ServiceA
<h1>Hello, world!</h1>


 @functions{
     protected override void   OnInit()
     {
         ServiceA.showMessage();
     }
 } 
```

**Comment by chrissainty** [comment]
Hi @iAmBipinPaul, 

I can't replicate this. There is an issue with the code you've provided though. You are injecting the `ToastService` into `ServiceA` but `ToastService` is scoped and `ServiceA` is singleton. You can't inject a scoped service into a singleton. 

Could that be the issue?

**Comment by iAmBipinPaul** [comment]
Thank you !
I will try to make `ServiceA` as scoped , If it will work that will be awesome.
Otherwise I will prepare sample project.

**Comment by iAmBipinPaul** [comment]
Hi @chrissainty 
Yes, it was not working due to  service life time.(singleton).

In the client side Blazor application which will be more efficient , singleton  or scoped ?

**Comment by chrissainty** [comment]
I would go with scoped in client-side, but with client-side Blazor Scoped and Singleton act exactly the same. Might be worth giving this post I wrote about service lifetimes in Blazor a read for a more indepth explanation https://chrissainty.com/service-lifetimes-in-blazor/
