### ISSUE TITLE
[Question] New NuGet release

### ISSUE THREAD

**Issue by nheath99** [Blazored/Toast#122]
Would it be possible to release a new version to NuGet with the latest changes?

**Comment by linkdotnet** [comment]
Is there any maintainer left for the project? I feel like issues / PR aren't getting any attention anymore.
Is there a chance to elect new maintainer to drive the project fruther? @chrissainty

**Comment by chrissainty** [comment]
@linkdotnet I'm very much still here. At the moment the only unreleased change is a new onclick handler. Toast is having some larger work done on it by myself and a college and once this is done it will form a new major release. Regarding your PR, I have scanned it but it doesn't address the issue which you've tagged. That issue requests that the close icon be customisable and removable. A note which I'll add to that PR.

**Comment by linkdotnet** [comment]
Thanks for responding. @chrissainty I didn't mean my PR :D there is a open PR since February.
I very much support if you're still engaged with that project

**Comment by nheath99** [comment]
Thanks for responding @chrissainty, the onclick handler is what I'm interested in :) No pressure though - I'm glad there's a new major release in the pipeline as Toasts is so useful it's become a standard UI element in all my Blazor projects.
