### ISSUE TITLE
[Bug] Not displaying color

### ISSUE THREAD

**Issue by Davinel17** [Blazored/Toast#124]
i always have this on display , i dont know why , somoene can help ? 

![image](https://user-images.githubusercontent.com/59382061/128644092-ccfae8e0-cc22-447e-89a1-c840ab889574.png)
thank you

**Comment by Davinel17** [comment]
i also put in the config to be in the top right  and it still at the top left

**Comment by chrissainty** [comment]
It looks like the styling hasn't been loaded. If you can provide some code or a working repro of the issue it would make life a lot easier to diagnose the problem.

**Comment by chrissainty** [comment]
Closing this as no further communication from the author.
