### ISSUE TITLE
Removing the heading tag? onClick param?

### ISSUE THREAD

**Issue by segalxandr** [Blazored/Toast#132]
I got 3.1.2 from Nuget. 
The props for **ShowCloseButton**, **ShowCloseButton**, **CloseButtonContent** are not available in **BlazoredToasts** component.
Also not available is **onClick** in the **IToastService** **ShowInfo**. 
Most importantly I am _unable to get rid of the heading_ inside the toast by passing an empty string or null - still get a heading tag e.g. "INFO", "WARNING". **_How can I make it go away?_** Setting a custom heading works fine.
Any tips - thanks in advance!

**Comment by chrissainty** [comment]
Hi @segalxandr,

Could you provide a minimal repro with the issues you've highlighted? That way we can have a look into it and see what's up.

**Comment by segalxandr** [comment]
Hi @chrissainty !
Thanks for responding - [https://i.imgur.com/jPK9ajK.png](url) - this shows ShowClosButton prop not being available for me. The same is the issue with the CloseButtonContent - without those properties everything is fine. Again the version I have is 3.1.2.

The header always shows - either the custom text if you supply it or caps for whatever the toast's type is, e.g. INFO, WARNING, etc. But I found a workaround in one of the comments and I am supplying my toast's message in the header's parameter, and leaving the message parameter empty - _toastService.ShowInfo("","This is my toast" ). To get rid of the caps - I have to override the CSS. 

Great component - many thanks! Cheers.

**Comment by chrissainty** [comment]
Hi @segalxandr I think something when wrong with out CI pipeline and the version of the package on NuGet isn't the code shown in the 3.1.2 release on GitHub. This is why you're not seeing the newer features. I'll get this sorted as soon as possible,
