### ISSUE TITLE
[Feature] Change position of toast when showing toast

### ISSUE THREAD

**Issue by JerseyTechGuy** [Blazored/Toast#159]
Would love to see the ability to change the position of the toast when showing it.  I know there are times I would like to move it from the lower right to top center to be more prominent.

Perhaps something as simple as this. Otherwise it uses the default set on the BlazoredToasts component Position property

`void ShowToast(ToastLevel level, string message, string heading = "", ToastPosition position);`

**Comment by Cvijo** [comment]
I manage to get this working can make PR if @chrissainty is ok with it


https://user-images.githubusercontent.com/506853/219494982-107fba7b-5e70-4033-bb5e-d85009a40e3c.mp4

**Comment by chrissainty** [comment]
@Cvijo Yes, more than happy for a PR on this one.
