### ISSUE TITLE
option to set toast  position on fly.

### ISSUE THREAD

**Issue by iAmBipinPaul** [Blazored/Toast#16]
I have changes related to this on my local machine , but It changes the position of all the other toast messages as well.

![6Al56r9GSA](https://user-images.githubusercontent.com/9201481/57971730-79bb4880-79b1-11e9-8426-c6389f014a28.gif)

**Comment by chrissainty** [comment]
Yes, the toasts container is currently global (only one), and all toasts load into it. I think this one might require a bit more thought. 

We'll have to look at creating new containers depending on the settings of a specific toast. But if two toasts have the same settings then reusing the existing container.

**Comment by iAmBipinPaul** [comment]
Okay , I will try to work on this.If I will have any progress on this I will update here.
Thank you !

**Comment by peterblazejewicz** [comment]
This could be probably implemented by delegating positioning to toast instance by additional component settings moved from container to instances (widen up container to `100vw`, position toast using flexbox layout with auto margins, add media query breakpoints to change layout on small devices removing all custom margins). The screenshots uses modified markup and css only:

<img width="1434" alt="Screenshot 2019-07-19 at 08 35 47" src="https://user-images.githubusercontent.com/14539/61514730-fba30e80-aa00-11e9-8055-d76a586a6e1b.png">

@chrissainty 
Let me know if this sounds plausible, I'd do the PR with change to review. There is no such feature in the `toaster.js` for example. The position change gets applied after currents toasts are removed from container

**Comment by chrissainty** [comment]
Looks good @peterblazejewicz. When the positioning is moved to the toast instance, what happens to the ability to click out side of a toast instance? 

I played with a similar idea a while ago and found that it blocked all click events to the rest of the page as the toast container was taking up the whole view port.

**Comment by peterblazejewicz** [comment]
> I played with a similar idea a while ago and found that it blocked all click events to the rest of the page as the toast container was taking up the whole view port.

We could rely on `pointer-events: none;` applied to container element and `pointer-events: all` applied to toasts element, somehow simplified example pen:
https://codepen.io/blazejewicz/pen/QebzoE

**Comment by chrissainty** [comment]
Oooh, that’s nice @peterblazejewicz! Looks like a decent solution. A quick check with CanIUse.com and its over 97% available. Which I’m certainly happy with.

**Comment by chrissainty** [comment]
This isn't something I've had time to get to and there doesn't seem to be a whole lot of interest in the feature. Based on that I'm going to close this issue if it's something people really want we can reopen it in the future.
