### ISSUE TITLE
[Question] Line breaks in Toast message?

### ISSUE THREAD

**Issue by Buriska** [Blazored/Toast#163]
Not sure if I'm just being obtuse but is there a way to use line breaks in the Toast message? Tried NewLine and '/n' with no luck.

Thank you

**Comment by chrissainty** [comment]
Please check the disucssions section as this question is covered there.

**Comment by frankvoelker** [comment]
How about you link the duplicate if this is an duplicate and how about you link the topic in discussion if this is covered in discussion and how about you write an one-liner code snippet if this is already solved?
