### ISSUE TITLE
Capital header is displayed when header is set to null

### ISSUE THREAD

**Issue by ltemimi** [Blazored/Toast#167]
I wanted to show a warning without a header by setting the header="" but I still see "WARNING" please help as I expect to see no header at all

Thanks

**Comment by chrissainty** [comment]
Hi @ltemimi. Unfortunately, headings are always displayed. If no heading is provided the default heading is shown. 

The only way to get round this is to use the custom toast option. This is where you specify your own toast component to display. This gives you complete control over the look of your toasts. 

You can find an example in the sample sites, as well as in the readme.
