### ISSUE TITLE
Responsive design for narrow screens (portrait mode)

### ISSUE THREAD

**Issue by MadTiger2409** [Blazored/Toast#17]
On devices with narrow screen (like smartphones in portrait mode) toast is too wide. It will be nice to see a responsive design in it.

---

Portrait mode:
![obraz](https://user-images.githubusercontent.com/24303774/58684511-cff89600-8378-11e9-9999-f3c0903fe05f.png)

---

Wide screen (desktop):
![obraz](https://user-images.githubusercontent.com/24303774/58684566-f6b6cc80-8378-11e9-86f5-20e69b33a5df.png)

**Comment by chrissainty** [comment]
Thanks for raising this issue @MadTiger2409. You can override the existing CSS to make toasts responsive if you want a quick solution.

I will see what I can do about making things responsive by default. Also happy to take a PR for this 😄

**Comment by MadTiger2409** [comment]
I will look into CSS for this toast in my free time. Maybe even create PR ;)

**Comment by chrissainty** [comment]
@MadTiger2409 I ended up having some time this evening so I've made some updates to make the toasts work better on smaller devices.

**Comment by MadTiger2409** [comment]
@chrissainty Is this fix a part of version 1.2.0? Because made an update in my project and nothing has changed.

**Comment by chrissainty** [comment]
Yes, the changes were in the 1.2.0 release. Have you cleared your cache?

**Comment by MadTiger2409** [comment]
@chrissainty My bad. I forgot about this, sorry 🤣 😄

**Comment by chrissainty** [comment]
@MadTiger2409 Happens to the best of us 🤣
