### ISSUE TITLE
ClearAll() does only clear List but not Queue

### ISSUE THREAD

**Issue by Flatscha** [Blazored/Toast#175]
I have a max toastcount of 3 which get displayed for 3 seconds.
If I get more than 3 messages in 3 seconds they get queued which builds up endlessly.
When I call ClearAll() the 3 toasts shown at the moment getting cleared but old messages still getting dequeued.

Please implement a ClearQueue() - method to fix this problem

Thanks in advance!

**Comment by chrissainty** [comment]
Hi @Flatscha, this looks like a good suggestion. I agree that adding it as an additional method is the best approach. Are you willing to create a PR for this?

**Comment by Flatscha** [comment]
Hi @chrissainty, sure!
Should ClearAll stay the same or should it be modified and clear the list and the queue?

**Comment by chrissainty** [comment]
I'd prefer not to change `ClearAll` as that would be a breaking change. I think we should just add a new method to clear the queue. I think any interesting design question is if the new message should just clear the queue and not active toasts, as that's already covered by the existing method. Developers can then call both if they want to remove everything.

Do you have any thoughts?

**Comment by Flatscha** [comment]
Hey @chrissainty,
could you please review my changes?
Thanks.

**Comment by chrissainty** [comment]
Resolved by #176
