### ISSUE TITLE
Anybody have trouble getting Icon to show or having background of Toast not white?

### ISSUE THREAD

**Issue by davem7714** [Blazored/Toast#184]
I think I have everything setup correctly to use Blazored.Toast:

From my MainLayout.razor page:
```
@using Blazored.Toast.Configuration

<BlazoredToasts Position="ToastPosition.BottomRight"
                Timeout="3"
                IconType="IconType.FontAwesome"
                ErrorIcon="error_outline"
                InfoIcon="info"
                SuccessIcon="fa-solid fa-check"
                WarningIcon="warning"
                ShowProgressBar="@true"
                ShowCloseButton="@true"
                MaxToastCount="3">
    <CloseButtonContent>
        <div>
            <span class="myCloseButtonStyleClass">&times;</span>
        </div>
    </CloseButtonContent>
</BlazoredToasts>
```

I've been trying different things with the SuccessIcon but no matter which type of Toast I try, no icon shows up.

In my razor page I have the following:
`@inject IToastService toastService`

and
```
<h1>Blazored Toasts</h1>

<button class="btn btn-info" @onclick="@(() => toastService.ShowInfo("I'm an INFO message"))">Info Toast</button>
<button class="btn btn-success" @onclick="@(() => toastService.ShowSuccess("Referral has been saved!"))">Success Toast</button>
<button class="btn btn-warning" @onclick="@(() => toastService.ShowWarning("I'm a WARNING message"))">Warning Toast</button>
<button class="btn btn-danger" @onclick="@(() => toastService.ShowError("I'm an ERROR message"))">Error Toast</button>
```

Result for Success Toast:
![image](https://user-images.githubusercontent.com/57457458/211056613-c6fc4a95-b2c8-4414-a198-a15f0eca2f64.png)

Results for Info Toast:
![image](https://user-images.githubusercontent.com/57457458/211056790-fa866bfc-7f6f-42e3-b1a1-ecd9ae0b2477.png)

Here is what I have in my CSS folder:
![image](https://user-images.githubusercontent.com/57457458/211057053-8b13bd06-6d8a-4aef-b0c9-54e507b9397c.png)

I'm registering the following:
```
      builder.Services.AddBlazoredModal();
      builder.Services.AddBlazoredToast();
```

Here are my references:
![image](https://user-images.githubusercontent.com/57457458/211057546-6088b694-bc38-47fc-bdc9-2cd1723d2dc1.png)

I'd like to be able to have a Toast with white body and the color at the top as well as showing the appropriate Icon.

Similar to what is shown here:
![image](https://user-images.githubusercontent.com/57457458/211058511-2a43bf3c-8561-4d3a-a20c-3ed881fddea8.png)

I also noticed that the Title (INFO, SUCCESS, WARNING and ERROR) aren't displaying.  Maybe all I need to do is to create custom toasts.

Any help would be appreciated.

**Comment by chrissainty** [comment]
@davem7714 you have a mix of the old and new versions there. The first screenshot with toasts with solid colour is the pre-v4 version. The white toasts with coloured highlights are v4. 

If you want v4 you don't need to supply any icons, you don't event need to provide the icon type.

**Comment by davem7714** [comment]
Do I just need to uninstall 3.2.2 and then install 4.0.0 ?

**Comment by chrissainty** [comment]
Yes. Sorry I missed the package version on your screenshot.

**Comment by davem7714** [comment]
That did the trick.  Thanks!
