### ISSUE TITLE
Blazored.Modal.css & Blazored.Toast.css files not loaded and showing 404 error

### ISSUE THREAD

**Issue by vinodpotru** [Blazored/Toast#189]
**Describe the bug**
Blazored.Modal.css & Blazored.Toast.css files not loaded and showing **_Failed to load resource: the server responded with a status of 404() _** Error in development environment

**To Reproduce**
I have update the application from .net5.0 to .net6.0 then i can see these errors

![image](https://user-images.githubusercontent.com/68293272/213442916-d815ff5b-cce0-4da2-bf07-3717ae71088b.png)

when i run the application 
![image](https://user-images.githubusercontent.com/68293272/213443163-cbfde2ed-c8a9-41a1-8c2e-bdde213b9660.png)
----
![image](https://user-images.githubusercontent.com/68293272/213443316-e6a114b6-4d18-4b81-b107-3d9edfceef1c.png)

**Expected behavior**
Blazored.Modal.css & Blazored.Toast.css files should load

**Comment by chrissainty** [comment]
Please read the readme files for both projects. It explains how to correctly reference the CSS file as we now use CSS isolation.

**Comment by vinodpotru** [comment]
Hi @chrissainty,  I mentioned the right path previously its working when i used .net5,0

![image](https://user-images.githubusercontent.com/68293272/213475428-643b6381-3def-4e57-bda6-238d0cf02918.png)

but i am not sure why i am getting this error

**Comment by chrissainty** [comment]
I'm guessing something is cached. There are no CSS files at those locations in the latest versions.

**Comment by vinodpotru** [comment]
@chrissainty , In Devlopment environment, i Cleared all the caches and deleted build files and rebuild & run the application but still its showing same error

**Comment by chrissainty** [comment]
The version of Modal you're using doesn't use that CSS file. From version 7 onwards it uses CSS isolation. See the readme on how to include that.

I didn't realise you weren't on the latest version of toast. I'm not sure why that isn't working. However, I'd suggest updating to the latest version and seeing if you still have an issue.

**Comment by vinodpotru** [comment]
I tried with all latest versions as well but still same @chrissainty
