### ISSUE TITLE
Option to configure fade in time

### ISSUE THREAD

**Issue by xJonathanLEI** [Blazored/Toast#19]
Currently the fade-in time of a toast is 1.5 seconds, hard coded in the CSS file:

```
.blazored-toast {
    display: flex;
    flex-direction: row;
    animation: fadein 1.5s;
    margin-bottom: 1rem;
    padding: 1rem 1.25rem;
    color: #fff;
    width: 30rem;
    border-radius: .25rem;
    font-family: monospace;
    box-shadow: rgba(0,0,0,0.25) 0px 10px 40px;
}
```

Is it possible to make it configurable with the use of dynamic CSS, something like [this](https://chanan.github.io/BlazorStyled)?

**Comment by chrissainty** [comment]
It's certainly possible, however, I'm not sure about mixing raw styles with C#. This feels very much like the approach React has with mixing styling and JavaScript. I personally prefer to keep concerns defined. Styling is best handled by stylesheets and logic by C#. 

In this case, overriding the `blazored-toast` class and changing the fade-in time is the correct way to customise this option. Is there any reason this can't work for your use case?

**Comment by chrissainty** [comment]
With the latest version there is now the ability to override the various toast types default styles. This should allow you to customise the fade-in time however you see fit. So I'm going to go ahead and close this issue. If you're still unable to achieve what you want then please reopen.
