### ISSUE TITLE
[Bug] Performance impact while using the latest release version

### ISSUE THREAD

**Issue by ab-cc** [Blazored/Toast#190]
**Describe the bug**
Hi Team, the startup time for the Blazor Server Application is increasing by 15 seconds or more with the new version v4.0.0. I have been using v3.2.2 in my app and have upgraded to v4 today, and immediately I can see increase in the app startup time.

**To Reproduce**
Steps to reproduce the behavior: You can use the sample weather app and incorporate Blazored.Toast into the app. Trigger a toast in the Index.razor page.

**Expected behavior**
No performance impact compared to older versions, definitely not 15s+

**Screenshots**
Using the MS sample weather app for Blazor Server, triggering toast in Index.razor, total time: 16344ms
![image](https://user-images.githubusercontent.com/45005187/213805768-5b56b048-3575-4166-a995-e42d0d4155e0.png)
![image](https://user-images.githubusercontent.com/45005187/213807813-176d969d-f09e-4c21-9e96-84849548174e.png)

Once I comment the toast, total time: 3743ms
![image](https://user-images.githubusercontent.com/45005187/213806423-2516480e-5092-40c4-b18e-b7445e43b059.png)
![image](https://user-images.githubusercontent.com/45005187/213806640-72937513-f5b0-416e-a139-017037a12723.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server
 - Running locally from Visual Studio IIS Express

**Additional context**
The startup time can clearly be traced to the toast notification.

**Comment by ab-cc** [comment]
Follow-up: I have downgraded the version to 3.2.2, and the performance issue is gone.

![image](https://user-images.githubusercontent.com/45005187/213844433-2d571904-678a-4735-bb1b-dc4122bbc49e.png)

**Comment by chrissainty** [comment]
Hi @ab-cc. APologies for not getting to this sooner. 

I've followed your repo steps and I'm not seeing any performance issues with the library. This looks like there is some local issue. If you can repro the results on another machine I can take another look but for now I'm going to close this.
