### ISSUE TITLE
[Bug] No overload method for custom heading?

### ISSUE THREAD

**Issue by flamecrow** [Blazored/Toast#191]
**Describe the bug**
README says you can use
`toastService.ShowSuccess("I'm` a SUCCESS message with a custom title", `"Congratulations!"))`
However, there is no such overload method that takes two strings like this (breaking change from version 3.2.2). 
Second parameter is now looking for
` Action<ToastSettings>? settings = null`

**To Reproduce**
1. Create project
2. Try to pass two strings to toast for "message" and "custom header"

**Expected behavior**
Allow passing two strings to toast to show message and custom header.

**Screenshots**
![image](https://user-images.githubusercontent.com/20115963/214137030-36182e8b-9115-4d56-8d33-9ef7c5642539.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server
 - Blazor WebAssembly

**Comment by chrissainty** [comment]
Good spot, thanks @flamecrow. I missed that when updating the docs. I'll get a PR raised in a sec to update that call and remove the custom title.

**Comment by Skyl3lazer** [comment]
Is it intended that we can no longer customize the toasts like this, or is there another way to do it now? I used this feature extensively.

**Comment by chrissainty** [comment]
Custom headings have been removed. There is just the message now. If you want to use a heading as well as a message then you can use the custom component option.
