### ISSUE TITLE
[Bug] Per instance timeout not working

### ISSUE THREAD

**Issue by positiveactionsvcs** [Blazored/Toast#195]
On 4.0.0 if I try to pass through a custom timeout value for a particular Toast, it doesn't work and always uses the Timeout value specified in the BlazoredToasts tag.

**To Reproduce**
In the Blazored.Toast samples just modify the first toast to say:

`<button class="btn btn-info" @onclick="@(() => toastService.ShowInfo("I'm an INFO message", settings => settings.Timeout = 100))">Info Toast</button>`

**Expected behaviour**
The Toast appears for 100 seconds.,

**Actual behaviour**
The Toast appears for 10 seconds.

The same seems to happen for both Blazor Server and Blazor WebAssembly.

**Comment by Cvijo** [comment]
seams there is a  bug is in BlatoredToasts.razor.cs in method `BuildToastSettings`

            ToastLevel.Error => new ToastSettings(
                "blazored-toast-error", 
                toastInstanceSettings.IconType ?? IconType, 
                toastInstanceSettings.Icon ?? ErrorIcon ?? "", 
                ShowProgressBar,
                ShowCloseButton,
                toastInstanceSettings.OnClick,
               ` Timeout `
                toastInstanceSettings.PauseProgressOnHover),

should be 
`toastInstanceSettings.Timeout == 0 ? Timeout : toastInstanceSettings.Timeout`

**Comment by chrissainty** [comment]
Thanks for finding that @Cvijo.
