### ISSUE TITLE
Adding Position to ToastSettings

### ISSUE THREAD

**Issue by Cvijo** [Blazored/Toast#196]
First of all great package !!

It would be great to have position passed to Toast from settings. Now you can set it for entire app once, but for some use cases it would be nice to have some information on different places, for example error toast in top center, and some info on bottom right.

I know there is List of toasts that have position set OnInitialize, maybe to have group of Lists by position ?

**Comment by Cvijo** [comment]
sorry i just found it this feature request already exists, a Duplicate of [159](https://github.com/Blazored/Toast/issues/159)

**Comment by chrissainty** [comment]
Closing as dup of #159
