### ISSUE TITLE
Css question

### ISSUE THREAD

**Issue by carlhoogstoel** [Blazored/Toast#200]
I saw in one of the posts that you suggested just to override the css classes if you want to tweek something. I did what you suggested but my custom css is no taken into account.

As you can see from the screenshots, I added the custom css to my own css file, its loaded and the css isolation is also working as expected.

Can you maybe point me in the right direction as to what I am missing?

![toest issue](https://user-images.githubusercontent.com/19626310/218454161-6c7fce8a-7ee9-4bc2-9116-c8487ef9db67.png)

**Comment by chrissainty** [comment]
If you inspect the toast and look at the styles tab, are your styles being applied or are they being overriden by something else?

**Comment by carlhoogstoel** [comment]
Don't think so. Yours are at the top.

![image](https://user-images.githubusercontent.com/19626310/218500182-3f4f0764-6a72-4f87-b9a8-8fb7c720abd5.png)

**Comment by carlhoogstoel** [comment]
This seems to be better

![image](https://user-images.githubusercontent.com/19626310/218522810-434b30a2-058d-4bb0-971b-aa85a07da571.png)

**Comment by chrissainty** [comment]
Cool. So adding !important solved it and applied your styles.

**Comment by chrissainty** [comment]
Going to close this as the issues seems to be resolved.
