### ISSUE TITLE
Getting in contact

### ISSUE THREAD

**Issue by Garderoben** [Blazored/Toast#21]
Hey,

Not really an issue but i wanted to get in contact with you. I have used your Toast as a base and modified it to work more like a snackbar and added a new type for background jobs where the snackbar does not close until job is done and with loader animations etc. Upon close it destroys the worker info snackbar and shows Success/Error.

Is it okay with you if i upload it to my github? and of course give you full credit for all the base work.

**Comment by MadTiger2409** [comment]
@Garderoben Maybe you could make this as a second mode of this component (with ability to switch mode) and create a pull request.

**Comment by chrissainty** [comment]
Hi @Garderoben, sorry for the long reply I've been away for the last few days. 

Great to hear you've created something on top of Blazored.Toast! Of course it's fine to upload. As @MadTiger2409 suggests, would you be interested in exploring adding it as a mode of the toast? Or even adding to the Blazored collection?

**Comment by chrissainty** [comment]
I'm going to go ahead and close this issue, but please feel free to get back to me if you want to explore adding to it the existing control or adding it as a new control.
