### ISSUE TITLE
[Bug] White bar at top of custom alert

### ISSUE THREAD

**Issue by ShawnDoe** [Blazored/Toast#217]
**Describe the bug**
There is a white bar along the top of the custom toast. I saw this on my own project then confirmed it on the project downloaded from here.
**To Reproduce**
Download the sample project here.
Run it.
Choose Custom Toast.
See white bar along the top of the toast.
**Expected behavior**
I cannot override whatever this is and I would expect to be able to remove it.

**Screenshots**
![image](https://user-images.githubusercontent.com/4106874/235754520-a621f7f4-2582-4776-ad91-4e757a9eb693.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Additional context**

**Comment by Cvijo** [comment]
A workaround would be to add CSS to override blazored-toast with {border-top:0px;} on your custom component

**Comment by taylorchasewhite** [comment]
Same
