### ISSUE TITLE
Possible to include Icons with the Toast (Checkmark, X, etc)

### ISSUE THREAD

**Issue by aherrick** [Blazored/Toast#22]
Is it possible to include icons similar to this project? I'm using Blazored Toast because it supports Server side :)
https://blazor-toaster.sotsera.com/

**Comment by chrissainty** [comment]
This is definitely possible. Where about would you like to be able to set icons? Just to the left of the main text, like in the library you linked to?

**Comment by aherrick** [comment]
Hi @chrissainty Yep I think that makes sense it just adds a little extra pop to the toast :)

**Comment by chrissainty** [comment]
I'm now about to merge a PR with a few improvements including the icon option you've requested @aherrick. Should hit NuGet in the next half hour.
