### ISSUE TITLE
Rendering Toast in cshtml or firing the toast from cshtml.cs

### ISSUE THREAD

**Issue by VitalJeevanjot** [Blazored/Toast#220]
Hi,

Thankyou for this awesome package. I am new in Blazor development and creating my first Blazor-server project.
I have Scaffolded Register.cshtml(cshtml.cs) files from Identity to add a custom check before moving forward in OnPostAsync().
The toast works file from Razor component like index.razor but through cshtml or cshtml.cs it didn't show up.

![image](https://github.com/Blazored/Toast/assets/40867747/9e0b5d14-2b1e-4b9f-93a7-1dc15dcfef91)

I am at first steps in "web-development in C#". Thank you.

**Comment by chrissainty** [comment]
Hi @VitalJeevanjot. This package only works in Blazor components, not in Razor Pages or MVC views.

**Comment by VitalJeevanjot** [comment]
Ok thanks @chrissainty
