### ISSUE TITLE
[Bug] Additional Classes for Warning / Info / Success / etc. Toasts are no longer applied

### ISSUE THREAD

**Issue by taylorchasewhite** [Blazored/Toast#221]
**Describe the bug**
Using the `WarningClass`, `InfoClass`, `ErrorClass`, and `SuccessClass` no longer applies the specified classes to the toast.

**To Reproduce**
1. In MainLayout.razor (or wherever `BlazoredToasts` is consumed), use custom classes for your toasts:
```
<BlazoredToasts Position="ToastPosition.BottomRight"
				ErrorClass="alert alert-danger"
				ErrorIcon="fas fa-times-circle"
				SuccessClass="alert alert-success"
				SuccessIcon="fas fa-check"
				WarningClass="alert alert-warning"
				WarningIcon="fas fa-exclamation-triangle"
				InfoClass="alert alert-info"
				IconType="Blazored.Toast.Configuration.IconType.FontAwesome" />
```
2. Launch a toast and see the class(es) no longer are applied.

**Expected behavior**
Append the specified string in `WarningClass` (and others) to the rendered BlazoredToast component's class list (e.g. apply to ToastSettings object).

**Hosting Model (is this issue happening with a certain hosting model?):**
All hosting models.

**Additional context**
It looks like this happened in #181 in commit [2a3eaa4](https://github.com/Blazored/Toast/pull/181/commits/2a3eaa465dd28f2cad2f96fe9cb91de052a3c140#diff-1bc74599ebe0655c025e924e38e0c5aae97a4ac2320e5b5816f1e271556dec70L103) where we changed the ToastSettings initializer to be multi-line, the additional class logic was dropped.

**Comment by taylorchasewhite** [comment]
If this is as straightforward as returning that (presumably) inadvertently removed logic, I'd be happy to take a stab at it and open a PR.

**Comment by JeremySayers** [comment]
Also ran into this tonight using the latest version.

**Comment by taylorchasewhite** [comment]
@JeremySayers, I decided to go ahead and stick with updated my packages. To get around this issue until #222 gets merged in I just added more specific styles to the default classes applied. Here are the class names:

- `.blazored-toast-warning`
- `.blazored-toast-info`
- `.blazored-toast-error`
- `.blazored-toast-success`
