### ISSUE TITLE
No Toast Notification in Safari 16.5.1

### ISSUE THREAD

**Issue by danijeljw-RPC** [Blazored/Toast#227]
**Describe the bug**
Toast notifications do not appear in Safari 16.5.1 from Blazor client-server hosted app _(on client)_

**To Reproduce**
1. Install Blazored.Toast service
2. Create a button using provided code
3. Tested OK in Edge/Chrome
4. Tested and nothing happened in Safari

**Expected behavior**
A notification to appear

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor server/client/shared project
 - Installed in Client application
 - Works on other browsers

**Comment by taylorchasewhite** [comment]
Are you able to inspect the DOM and see if there are any console errors, and if not, if the DOM is being modified as expected (e.g. the modal containers and modal content shows up in the DOM but is not visible, or if it's not updating the DOM)? The two fixes are fairly different.

Also, please share if you have any customizations on the ToastSettings (classes, etc.) or you're just using the default content.

**Comment by chrissainty** [comment]
@danijeljw-RPC I've just tried your repro steps on Safari (16.5.2) and everything is working as expected. I'm not sure if this was a bug in Safari 16.5.1 and has been fixed or some local issue, but everything appears to be working OK now. 

I'm going to close this issue but if you see the problem again, please re-open it.
