### ISSUE TITLE
Is it possible to increase the z-index in BlazoredToasts.razor.css to zindex-tooltip (1080)?

### ISSUE THREAD

**Issue by Shecla** [Blazored/Toast#230]
When I call the toast from a modal poup it appears behide the popup and I can not access to close button.

**Comment by Shecla** [comment]
I suggest you to create a new Parameter in BlazoredToasts.razor.cs 
[Parameter] public string? Style { get; set; }
and use it as style in BlazoredToasts.razor
<div class="blazored-toast-container @positionGroupedToasts.Key" @key="positionGroupedToasts.Key" style="@Style">.

**Comment by Shecla** [comment]
"<div class="blazored-toast-container @positionGroupedToasts.Key" @key="positionGroupedToasts.Key" style="@Style">"

**Comment by chrissainty** [comment]
Hi @Shecla, if you want to increase the z-index you can override the default value via CSS. This won't be something that would be changed in the library.

**Comment by Shecla** [comment]
Can you show me how to do it?

**Comment by chrissainty** [comment]
This question has been covered in the discussions section and covers what CSS is needed to override. 

https://github.com/Blazored/Toast/discussions/128
