### ISSUE TITLE
[Feature Request] Stop timeout on mouse hover

### ISSUE THREAD

**Issue by luis-fss** [Blazored/Toast#233]
Stop the timeout when the mouse is over the toast, so the user would have all the time they want to read the content and wouldn't be frustrated by missing an important message.

**Comment by chrissainty** [comment]
@luis-fss This feature already exists. There is a setting 'PauseOnHover' which should do what you describe.

**Comment by luis-fss** [comment]
Thanks @chrissainty, I didn't find this on ReadMe page.

**Comment by chrissainty** [comment]
That's a good point @luis-fss, it should be in the readme. I'll open an issue for that.
