### ISSUE TITLE
Class parameter for toasts

### ISSUE THREAD

**Issue by MadTiger2409** [Blazored/Toast#24]
Currently, the only option to change the style of the toast is to edit the `blazored-toast.css` file.

I would like to see some parameters in `<BlazoredToasts />` component. I think that there can be a parameter for CSS class/classes for every type of toast, for example:

``` razor
<BlazoredToasts InfoClass = "my-custom-info-css-class" SuccessClass = "my-custom-success-css-class" WarningClass = "my-custom-warning-css-class" ErrorClass = "my-custom-error-css-class" />
```
(If you don't want to override style of the specific type of toast then you just don't use parameter that is responsible for this. For example you can remove `InfoClass = "my-custom-info-css-class"` so then Info Toast will have only it's default style.)

It shouldn't replace original css class but instead combine this two parts into something like this:
``` html
<div class= "blazored-toast warning my-custom-warning-css-class>
   ...
</div>
```
So in the end `my-custom-warning-css-class` will override some (or all) `blazored-toast warning` CSS settings with it's own.

**Comment by chrissainty** [comment]
I agree @MadTiger2409 there needs to be a nicer way to override the default. I'm now about to merge a PR with a few improvements including what you've requested above. Should hit NuGet in the next half hour.
