### ISSUE TITLE
[Question] How to get the old look-and-feel with headings back? Breaking change is preventing me from upgrading.

### ISSUE THREAD

**Issue by szalapski** [Blazored/Toast#240]
Is there any way to keep the ability to opt-back-in to toast with headings and the old styling/look from v3 when upgrading to v4?  My stakeholders don't want the change in look and feel, and also we have headings we don't want to lose.

I know I can rework my code to use a custom toast, but perhaps someone has done some of that already?  I don't think it is practical to change hundreds of invocations.  This is preventing me from upgrading.

see also https://github.com/Blazored/Toast/pull/181

cc @chrissainty

**Comment by hellfirehd** [comment]
This looks like it might be the solution, but will require a new release of the library.

https://stackoverflow.com/a/72223221/32588

**Comment by chrissainty** [comment]
@szalapski Unfortunately there is no way to opt back into the old look. As you have suggested, you could use the custom toast option to recreate it. However, I won't be changing the library to allow the old look. This is pretty common in UI libraries, every now and then the look is updated and you can either use it or stick with the previous version.

**Comment by szalapski** [comment]
I was able to convince them to accept the change so they could get custom timeouts.
