### ISSUE TITLE
[Bug] Progress bar & Close button not configurable on the fly.

### ISSUE THREAD

**Issue by Petit-Pas** [Blazored/Toast#241]
Hey there, 
I'm building a small project to serve as personal demo of all configuration capabilities of the library, trying to make every example in the provided sample configurable through checkboxes to test possibilities without code. 

My project is a basic .Net 8 web assembly app with the Blazored.Toast 4.1.0 installed. 

When I try to configure the settings of a given toast (by modifying the settings in a delegate as parameter to the ShowInfo() method) it does work well, except for ShowProgressBar & ShowCloseButton settings. Everything related to position and timeout works though. 

I tried doing the modifications in this (blazored) cloned repository, and it works. 
I tried modifying the setting globally in the <BlazoredToasts> balise in my repository and that works.
I tried copying the line 
`
<button class="btn btn-info" id="InfoButton" @onclick="@(() => ToastService.ShowInfo("I'm an INFO message", settings => { settings.IconType = IconType.None; settings.ShowProgressBar = true; }))">Info Toast</button>
`
Which is an lightly modified version of the 1st button of your demo in my repository, and it only works in the source repository, not in mine. 

Since the package was last updated 9 months ago and the repository was updated mor recently than that, would it be possible that there is a difference between the 2 version that is causing that ?

**Comment by chrissainty** [comment]
Hi @Petit-Pas,

You're correct. This was fixed with [this PR](https://github.com/Blazored/Toast/pull/226) but I want to get some other updates in before I do another released as well as upgrade everything for .NET 8. I just haven't had the time but I will get it done as soon as possible.

**Comment by Petit-Pas** [comment]
Hey @chrissainty, 
Thanks for the quick reply :) 
Any way you can release an alpha version in the meantime or is that something you don't quite do?
