### ISSUE TITLE
Not good looking

### ISSUE THREAD

**Issue by TinkuDhankhar** [Blazored/Toast#244]
1. PackageReference Include="Blazored.Toast" Version="4.0.0" 
2.
![image](https://github.com/Blazored/Toast/assets/52667071/c5e27c6a-a5a3-4f88-b277-fef8bee65791)
3.
![image](https://github.com/Blazored/Toast/assets/52667071/de0995fb-0df9-45a6-bd53-07cc6f1aca73)
4.
![image](https://github.com/Blazored/Toast/assets/52667071/29e5b2da-573e-4af3-bc8b-15e35f097f7b)

Dear team,
Can you please let me know how to fixed CSS related issues when i has fire any toast message. Then not showing good looking message on the Blazer application
Thanks

**Comment by chrissainty** [comment]
@TinkuDhankhar This will either be a caching issue in the browser or you have referenced the CSS bundle incorrectly.

**Comment by aherrick** [comment]
i had this issue too - just had to do a hard cache refresh in chrome
