### ISSUE TITLE
Z-Index Docs or Manipulation

### ISSUE THREAD

**Issue by vertonghenb** [Blazored/Toast#28]
In  certain apps, the Z-Index of the Toast Container is higher than the default z-Index. 
Let's document this behavior or add some docs on how to adjust it:

Todo: 
1. Re-evaluate the Z-Index value in our CSS (currently 1000)
2. Add parameter to the container or document the alternative route to use style.

**Comment by chrissainty** [comment]
Is the issue here that the Toast Container is blocking click events/interactions with the rest of the screen?

**Comment by vertonghenb** [comment]
Not really, the container is simply hidden because of the z-index of my header.

**Comment by chrissainty** [comment]
Yes, that might be worth putting in the readme. We could up the z-index to 9999 but I'm sure someone somewhere will have an element at 10000 then we're back to the same issue.

**Comment by vertonghenb** [comment]
True, I'll PR it.

**Comment by chrissainty** [comment]
Resolved by #32

**Comment by endstreet** [comment]
Why not just go above bootstrap reservations: 

$zindex-dropdown:          1000 !default;
$zindex-sticky:            1020 !default;
$zindex-fixed:             1030 !default;
$zindex-modal-backdrop:    1040 !default;
$zindex-modal:             1050 !default;
$zindex-popover:           1060 !default;
$zindex-tooltip:           1070 !default;

Most people will be happy...

**Comment by chrissainty** [comment]
We could but there are other CSS framework that have different z-index values. I'm happy to take a PR.
