### ISSUE TITLE
C# 8

### ISSUE THREAD

**Issue by frablaser** [Blazored/Toast#35]
Hi,
Great sample! 

But it has been made over C# 7.3 and we all know the .Net Core 3 will use C# 8. Setting the project to C# 8, by using the preview keyword or write it directly as:
```
<PropertyGroup>
   <LangVersion>preview</LangVersion>
</PropertyGroup>

or

<PropertyGroup>
   <LangVersion>8</LangVersion>
</PropertyGroup>

```

It insert the new C# 8 rules who are not compatible with your beautiful code like:
`<button class="btn btn-info" @onclick="@(() =>  toastService.ShowInfo("I'm an INFO message"))">Info Toast</button>`

Show a warning message as: 

> Error	CS1660	Cannot convert lambda expression to type 'object' because it is not a delegate type	BlazorServerSideSample	

If we try to insert an Action delegate :
`<button class="btn btn-info" @onclick="@(() =>  (Action<ToastService>)toastService.ShowInfo("I'm an INFO message"))">Info Toast</button>
`
It don't work too...

**Comment by chrissainty** [comment]
Hi @frablaser,

Apologies for taking so long to reply. While C# 8 is going to be awesome I don't think now is the time to make the swap over. But once things are a bit further along then we can take another look.

**Comment by frablaser** [comment]
Sure, until it will be in final release, it's useless to make the changes each time a new version comes out. But at the end, as soon as the production version is on the way, it would be great if you took the time to update it? ;) Thanks!
