### ISSUE TITLE
Maximum Items Parameter

### ISSUE THREAD

**Issue by vertonghenb** [Blazored/Toast#37]
Add a parameter to only show x amount of toasts at the same time.
For example, sometimes the user can get spammed with notifications. It would be handy to only show the last item.

**Comment by chrissainty** [comment]
Hey @vertonghenb, just sorting all the repos out and noticed that I'd neglected this issue, apologies.

Say 5 modals are shown in rapid succession, with this feature would you want each one to show still but only one at a time? Could you provide a bit more detail on how it should work.

**Comment by gosferano** [comment]
Was looking through submitted issues to find this one and I think what you described is exactly what the issue reporter meant, i.e., there would be a stack of toasts with configurable max element count.
