### ISSUE TITLE
blazored-toast.css not loading correctly in Production

### ISSUE THREAD

**Issue by dahln** [Blazored/Toast#39]
Steps to reproduce:

In a Web Assembly App, I added <link href="_content/Blazored.Toast/blazored-toast.css" rel="stylesheet" /> to the index.html page, as described in the documentation.

Toast messages appear as desired in the local dev environment. After publishing the app to an App Service on Azure, the blazored-toast.css does not load correctly.  This warning appears in the browser console: 
Resource interpreted as Stylesheet but transferred with MIME type text/html

When I inspect the call to load the css file, response contains the html of the index.html page.

The build and the deployment was done with Azure Dev Ops Pipelines. My current theory is that the _content folder does not exist after deployment.

**Comment by chrissainty** [comment]
Hi @dahln - It sounds like you may have hit this bug (https://github.com/aspnet/AspNetCore/issues/13103). Could you do a publish locally or check whats been deployed to your App Service to verify?

**Comment by dahln** [comment]
@chrissainty Thanks for getting back to me so quickly. The bug you referenced describes my problem. I verified it by checking the folders/files that exist on my App Service. I found the _content folder, with the blazored-toast.css in it. But the _content folder was under the wwwroot folder, not the dist folder. You can close this issue as a duplicate if you wish.

**Comment by chrissainty** [comment]
@dahln I've made a change in the latest version of this package which may get around the issue. Could you update to the latest version and see if the issue is resolved? 

Note: You won't have to reference the CSS file in you index.html anymore it will be added automatically for you.

**Comment by dahln** [comment]
I updated the package to the latest version. That worked great. Thank you. 

I think I prefer not having to add the css file to the html page, since it makes the implementation of the package even more simple.

**Comment by chrissainty** [comment]
I'm glad it's working for you.

**Comment by HARRIS-TARIQ** [comment]
The user has the page "https://localhost:7015/" open and an error message is shown in the DevTools Console for this page. The error message is wrapped within <DevToolsErrorMessage></DevToolsErrorMessage> below. Explain the error message and what could have caused it, and provide a way to fix it. <DevToolsErrorMessage>blazored-toast.css:1 Failed to load resource: the server responded with a status of 404 ()</DevToolsErrorMessage> Explain the error message from DevTools console blazored-toast.css:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by NLSon03** [comment]
> The user has the page "https://localhost:7015/" open and an error message is shown in the DevTools Console for this page. The error message is wrapped within below. Explain the error message and what could have caused it, and provide a way to fix it. blazored-toast.css:1 Failed to load resource: the server responded with a status of 404 () Explain the error message from DevTools console blazored-toast.css:1 Failed to load resource: the server responded with a status of 404 ()

Just delete the reference toast CSS in index.html
