### ISSUE TITLE
Toast not displaying when IToastService is injected into a non-component class

### ISSUE THREAD

**Issue by dahln** [Blazored/Toast#41]
I have created an example to demonstrate the issue I am seeing: https://github.com/dahln/Toast-PossibleIssue

In my app, I created an "ApiLibrary", to contain all my outgoing Api calls. I want to display a toast message if a server ever returns a 500 response message, and I want to use the IToastService in the injected "ApiLibrary" to invoke the message. If I call IToastService.ShowError on the page, it will display as expected. If I try to call the same method in the "ApiLibrary" it doesn't work. The ApiLibrary is injected into page. I verified that the method in the "ApiLibrary" is being called successfully, but the toast isn't being displayed.

**Comment by iAmBipinPaul** [comment]
Hi , @dahln  I see you have register your `ApiLibrary` as Singleton. Try adding   `ApiLibrary`  as scoped , it should work.

![image](https://user-images.githubusercontent.com/9201481/66033001-209a1e80-e526-11e9-95ff-b861d7b76bce.png)


https://github.com/dahln/Toast-PossibleIssue/blob/3b1c76114a8db82d346c091a9e9a5e7949496e2c/BlazorToastPlayground/Startup.cs#L13

**Comment by dahln** [comment]
@iAmBipinPaul Your suggestion worked. Switching the AddSingleton to AddScoped worked. I'll be honest, after trying this out, I went a reviewed the documentation from Microsoft on AddSingleton and AddScoped, and I still don't understand why this made a difference.

**Comment by chrissainty** [comment]
@dahln The reason is because Blazored Toast is added to the DI container with a scoped lifetime. You added your service as a singleton. You're not able to inject a scoped service into a singleton as it would effectively make that scoped service into a singleton. ASP.NET Core's DI container will throw an exception at this which is probably the error you were seeing.

**Comment by dahln** [comment]
That explanation helps. Thank you. I feel like this is resolved.
