### ISSUE TITLE
Style Updates To The Toast - Remove Monospace/Uppercase Text

### ISSUE THREAD

**Issue by taylorchasewhite** [Blazored/Toast#43]
Right now in the Toast stylesheet we set the header to uppercase with the following selector/style:
`blazored-toast-body .blazored-toast-header h5`/`text-transform: uppercase;`.

We also set the font-family to `monospace` in `.blazored-toast`.

Could we allow consumers to make these determinations separately with their own CSS overrides?

**Comment by chrissainty** [comment]
Agreed, this was some default styling that was used before this project was open sourced and just hadn't been removed. It makes sense to have these values inherit from the consumers defaults.

Happy for you to submit a PR for this change if you're interested, Taylor?

**Comment by taylorchasewhite** [comment]
Yessir, I’ll create and submit one this week, thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
