### ISSUE TITLE
blazored-toast.css Not Loading correctly in non-Dev Environments in Blazor Server project

### ISSUE THREAD

**Issue by rgamage** [Blazored/Toast#48]
It seems the _content folder items are not being referenced correctly for anything other than the Development environment:

To Repro: 
1) Create a new Blazor Server project (dotnet new blazorserver)
2) Add all necessary Blazored / Toast elements, including code to demo a toast message
3) Test that toast is working
4) Change launchSettings.json ASPNETCORE_ENVIRONMENT to Staging, Production, or anything other than Development
5) Run program again (using ISS Express local debug), and notice the css formatting is not correct
6) Change debug settings to use Kestrel instead (change IIS Express drop-down to BlazorApp1 or similar)
7) Notice with kestrel, css is working fine

**Comment by chrissainty** [comment]
Hi @rgamage, have you had this issue with other libraries? It seems like its more likely an issue with Blazor as there is no code in this library which reacts to environment variables.

**Comment by rgamage** [comment]
Yes, this issue occurs on any static files that are referenced in this way, I suspect.  This is just the first lib I'm using where I hit the issue.  Can you recommend a better place to post the issue?

**Comment by chrissainty** [comment]
It would be best to raise it with the [Blazor team](https://github.com/aspnet/aspnetcore).

**Comment by rgamage** [comment]
Asked and answered here:
[https://stackoverflow.com/questions/58862932/blazor-server-static-files-dont-link-in-non-dev-environments](https://stackoverflow.com/questions/58862932/blazor-server-static-files-dont-link-in-non-dev-environments)

**Comment by chrissainty** [comment]
Interesting, I didn't know that. Thanks for providing the link. I'm going to close this issue as it's all resolved.
