### ISSUE TITLE
Allow html content

### ISSUE THREAD

**Issue by rafalone** [Blazored/Toast#49]
Please, allow html content is needed, like <br /> tags.

**Comment by chrissainty** [comment]
Would you want to be able to pass in a component to be displayed? Or would you want to pass in a HTML string.

**Comment by rafalone** [comment]
I prefeer Html string.

Thanks Chris!!

**Comment by rafalone** [comment]
Please, add 

> MarkupString

 in **Message** and **Heading** params on _BlazoredToast.razor_.

`<p class="blazored-toast-message">@((MarkupString)ToastSettings.Message)</p>`

**Comment by chrissainty** [comment]
Why would this be useful in the heading? I can understand the need in the body section.

**Comment by thoemmi** [comment]
Having the option to use HTML tag (e.g. `<strong></strong>`) would be quite useful.

**Comment by chrissainty** [comment]
I'm just not sure how this is achievable with our current API. I wouldn't want to have developers passing strings with HTML tags, that's just an accident waiting to happen. 

I'm open to ideas if anyone has any?

**Comment by rafalone** [comment]
<ContentTemplate>

</ContentTemplate>

**Comment by chrissainty** [comment]
But we can’t do that toasts are shown via a C# API not a razor one. 

```
ToastService.ShowInfo(“”);
```

**Comment by rafalone** [comment]
https://blazor.syncfusion.com/documentation/toast/getting-started/?_ga=2.144560245.1376162098.1585160524-1255340030.1569306472

**Comment by chrissainty** [comment]
I’m not sure what you’re suggesting? As I said, we use a C# API, we don’t use components directly as is shown in that link.

**Comment by rafalone** [comment]
Passing a DOM element ref as content?

**Comment by thoemmi** [comment]
@chrissainty Why are you proposing against raw HTML, like in `<p class="blazored-toast-message">@((MarkupString)ToastSettings.Message)</p>`?

IMHO it's the responsibility of the user of Blazored.Toast to suppress malicious HTML. E.g. he can use [HtmlSanitizer](https://github.com/mganss/HtmlSanitizer) like this:

```csharp
var sanitizedHtml = HtmlSanitizer.Sanitize(Hello <strong>world</strong>!"");
ToastService.ShowInfo(sanitizedHtml);
```

**Comment by chrissainty** [comment]
@thoemmi Mainly because it's a horrible developer experience. Writing HTML into a string loses all the IntelliSense of an IDE, you lose any dev-time checking as well. Essentially it gives a problem/bug a place to hide.

I also appreciate what you're saying that it should be the developers responsibility to check for malicious HTML but it's an extra step they have to perform and people will miss it or forget and that could lead to a problem.

I'm not saying we should be a nanny for devs, but I would rather come up with a way of doing this which pushes devs into the pit of success rather than towards the pit of failure.

**Comment by thoemmi** [comment]
Well, I see your point. 

At the moment I'm prototyping another solution. How about an override of `ShowToast` which accepts a `RenderFragment`? Then you could write
```csharp
RenderFragment message = @<text>Hello <strong>World</strong>!</text>;
toastService.ShowToast(ToastLevel.Info, message);
```

What do you think about this approach?I'd be happy to provide a PR.
