### ISSUE TITLE
not working correctly in Razor components

### ISSUE THREAD

**Issue by uwefms** [Blazored/Toast#5]
I cannot run Toaster in server-side blazor. 

This is the csproj file of the client.app:
`<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Browser" Version="3.0.0-preview-19075-0444" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Build" Version="3.0.0-preview-19075-0444" PrivateAssets="all" />
    <PackageReference Include="Sotsera.Blazor.Toaster" Version="0.8.0-preview-2" />
  </ItemGroup>
</Project>`
 

I tried:

`
@page "/counter"
@inject IToastService toastService

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" onclick="@IncrementCount">Click me</button>

@functions {
    int currentCount = 0;

    void IncrementCount()
    {
        currentCount++;

        toastService.ShowToast(ToastLevel.Info, "Now at " + currentCount.ToString());
    }
}

`
In the counter component.

![toaster_rc_](https://user-images.githubusercontent.com/13874580/52772666-5b078780-3039-11e9-8cd1-a1aedc539dc2.jpg)

**Comment by chrissainty** [comment]
Hi @uwefms, I think this is actually a known limitation in the first preview of Razor Components. Static assets are not being included from component libraries. I think you're not getting the CSS loaded from Blazored Toast by the looks of it.

You can read more [here](https://blogs.msdn.microsoft.com/webdev/2019/01/29/aspnet-core-3-preview-2/#sharing-component-libraries).

**Comment by uwefms** [comment]
Thought so - so waiting for the next preview ...
