### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by hensleyrob** [Blazored/Toast#57]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a progress bar to the bottom of the Toast. Control whether it's enabled/disabled via parameter.

**Describe alternatives you've considered**
None

**Additional context**
https://codeseven.github.io/toastr/demo.html

**Comment by chrissainty** [comment]
This seems like a great idea, we'll look at getting it planned out.
