### ISSUE TITLE
[Feature Request] Remove any visible toasts on page navigation

### ISSUE THREAD

**Issue by HybridSolutions** [Blazored/Toast#61]
First of all, great job! 

I setup a quick test using the default Blazor App and Toast. Everything went ok and is working, except for a minor thing. When a toast is visible, if I change to another page, the toast is still visible. It would be great to have all the visible toasts cleared on page change or at least have a Clear() method so that I could do it manually.

Have you seen this behavior?

Thanks!

**Comment by chrissainty** [comment]
Hi, this isn’t a bug it’s how it was designed. The toasts show for a set time regardless of what else happens with the app. 

We can look at adding this as a new feature though.

**Comment by HybridSolutions** [comment]
That would be great! If you need some testing I'm available ;)

**Comment by mgutwein** [comment]
I like this idea but would still like it to be an option. There are times I want the toast to stick around.

**Comment by chrissainty** [comment]
I think the default would be for toasts to stick around. The option would allow them to be cleared if the developer wanted to.

**Comment by HybridSolutions** [comment]
Yes I agree too. Adding a ClearAll() method that would hide any visible toasts would be enough.

**Comment by chrissainty** [comment]
This is now released and available in the lastest package.

**Comment by HybridSolutions** [comment]
> This is now released and available in the lastest package.

Wow. That was fast. Thanks. I'll give it a go.
