### ISSUE TITLE
[Bug] Blazor Toast Timer Error

### ISSUE THREAD

**Issue by nssidhu** [Blazored/Toast#71]
I am using Blazor Hosted WebAssembly and getting this Error on the startup.

blazor.webassembly.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Invalid value '0' for parameter 'interval'.
System.ArgumentException: Invalid value '0' for parameter 'interval'.
  at System.Timers.Timer..ctor (System.Double interval) <0x2ce4bf0 + 0x0004e> in <filename unknown>:0 
  at Blazored.Toast.CountdownTimer.SetupTimer () <0x2ce07e0 + 0x0000a> in <filename unknown>:0 
  at Blazored.Toast.CountdownTimer..ctor (System.Int32 timeout) <0x2ce03f8 + 0x00036> in <filename unknown>:0 
  at Blazored.Toast.BlazoredToast.OnInitialized () <0x2ce0288 + 0x0000a> in <filename unknown>:0 
  at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync () <0x2ba63f0 + 0x00030> in <filename unknown>:0

**Comment by chrissainty** [comment]
The default value for the `Timeout` parameter is 5 so I'm guessing you've manually set that to 0?

**Comment by nssidhu** [comment]
Where do i set or initialize that value ?
    On Saturday, 16 May, 2020, 10:58:59 am GMT-5, Chris Sainty <notifications@github.com> wrote:  
 
 


The default value for the Timeout parameter is 5 so I'm guessing you've manually set that to 0?

**Comment by nssidhu** [comment]
I was putting the Toast at the bottom of the MainLayout.turns out that i have to put it up as the first thing ?It is working as expected once i put on the top of the MainLayout.
    On Saturday, 16 May, 2020, 10:58:59 am GMT-5, Chris Sainty <notifications@github.com> wrote:  
 
 


The default value for the Timeout parameter is 5 so I'm guessing you've manually set that to 0?

**Comment by chrissainty** [comment]
That shouldn't matter and definitely should effect the timer value. Are you sure you've not changed the setting for the `Timeout` parameter?

**Comment by nssidhu** [comment]
Yes, I did not change the timer value, I don’t even know where and how to change it.
I just saw you toast example where you have it on the top and I just copy pasted the at the bottom. It did not work.
Next I moved it to the top and it started working.



Sent from Yahoo Mail for iPhone


On Saturday, May 16, 2020, 11:36 AM, Chris Sainty <notifications@github.com> wrote:




That shouldn't matter and definitely should effect the timer value. Are you sure you've not changed the setting for the Timeout parameter?

**Comment by Springwald** [comment]
I had the same error.

The Reason was, that I did not include the component into the MainLayout.razor as written in the description but into another sub-component instead.

**Comment by chrissainty** [comment]
This looks like it turned out to be a configuration error. I'm going to go ahead and close this.

**Comment by vertonghenb** [comment]
For others having this issue, notice that 
`<BlazoredToasts/>` and not `<BlazoredToast/>` is used in the `MainLayout`

**Comment by zabronm** [comment]
> For others having this issue, check that `<BlazoredToasts/>` and not `<BlazoredToast/>` is used in the `MainLayout`

Hi guys, I had the same issue and this saved my day, thank you.
