### ISSUE TITLE
[Bug] bundleconfig.json added to project when installing NuGet package

### ISSUE THREAD

**Issue by darrylluther** [Blazored/Toast#72]
**Describe the bug**
We use TFS for source control and when I install the Blazored.Toast v3.1.1 NuGet package I am presented with the dialog shown in the attachment. It wants to add a bundleconfig.json to my project, but the path to that file is in the .nuget/packages/blazored-toast folder. No matter which selection I choose - "Add the item" or "Cancel add" - I get a bundleconfig.json file in the root of my project that I cannot remove. If I attempt to remove it I get an error: "Cannot modify an evaluated object originating in an imported file."

**To Reproduce**
1. Create a Blazor Server app and add to TFS source control.
2. Install the Blazored.Toast NuGet package.
3. See error

**Expected behavior**
The bundleconfig.json file should probably not be included in the distribution.

**Screenshots**
![blazored-toast](https://user-images.githubusercontent.com/4376954/82390664-29c3f700-99f4-11ea-9472-0ba6a1af62b7.png)

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server

**Comment by chrissainty** [comment]
Thanks for letting us know about this one @darrylluther. I'll take a look at this and get a fix out ASAP.

**Comment by chrissainty** [comment]
This has now been pushed to NuGet and should be available shortly.

**Comment by darrylluther** [comment]
Thanks for the super fast response, Chris. Really enjoying your libraries.
