### ISSUE TITLE
[Feature Request] Specify size of the toast.

### ISSUE THREAD

**Issue by Delpire** [Blazored/Toast#74]
**Is your feature request related to a problem? Please describe.**
Not exactly. The toasts are just really big and if the window is small can obstruct some text.

**Describe the solution you'd like**
I would like to be able to specify a specific size, or have different size options to choose from such as a more compact view.

**Describe alternatives you've considered**
I've thought about trying to override the css myself, but that seems like a bad solution. Alternatively, being able to remove the header could help.

**Additional context**
Additionally providing an offset could be nice.

**Comment by chrissainty** [comment]
Hi @Delpire, why do you feel overriding the CSS is a bad idea?

**Comment by Delpire** [comment]
@chrissainty  Hello! Perhaps just my lack of css experience. I can give it a try. I like how bootstrap often provides different classes I can pass to an html element to specify the size, I just thought it would be nice to provide this to the Blazored Toast element.

**Comment by chrissainty** [comment]
I understand where you’re coming from. The problem is what sizes do we provide? Small, medium, large? What’s small? What’s large? One persons small is another persons medium or vice versa. 

I’m open to ideas.

**Comment by Delpire** [comment]
Well right off the bat, having an option to remove the header would reduce the height. That being said, it probably isn't a good idea to depend purely on color.

I could see maybe providing a "compact" option where the padding is reduced, the font size is reduced, and perhaps the header and text could be on the same line. Kind of like how Slack provides Clean vs Compact messages:

![image](https://user-images.githubusercontent.com/8119571/83697940-c7f3b780-a5c5-11ea-9537-1f14a486cc47.png)

![image](https://user-images.githubusercontent.com/8119571/83697952-d17d1f80-a5c5-11ea-99cd-79952b0e8e56.png)

I think you are right though. It is a difficult thing to decide as far as fixed values.

An alternative would be to provide some levers that a user could customize. I just overrode the css by reducing the font-size and the width of the blazored-toast class. If these were parameters to the BlazoredToast component then a user could customize it. I'm not sure how well the support for this is in Blazor. It might have to be applied directly to the html, which with my limited understanding might be a bad decision.

![image](https://user-images.githubusercontent.com/8119571/83698104-389ad400-a5c6-11ea-99bc-77fc992c7da9.png)

Overall, I'm pretty new to Web UI design, so I am not very familiar with best practices, and Blazor is so new a lot of best practices probably haven't been determined yet. 😅

**Comment by chrissainty** [comment]
We could definitely expose some levers for people to tweak but if I’m honest, CSS does all of this. I’m reluctant to adds loads of options into the component and make the code far more complex when everything is infinitely customisable with CSS.

**Comment by Delpire** [comment]
That's fair. I am okay with this simply being closed.

One last option that I am also not sure about the feasibility of, would be to provide some kind of empty toast type that we could pass a render fragment to.

```
<Blazored.EmptyToast>
content...
</Blazored.EmptyToast>
```

Regardless, thank you for taking the time to discuss this!

**Comment by chrissainty** [comment]
@Delpire We have added a [custom toast](https://github.com/Blazored/Toast#custom-component) option now that might be of interest to you
