### ISSUE TITLE
[Feature] Add the ability to configure options per toast instance

### ISSUE THREAD

**Issue by drma-dev** [Blazored/Toast#75]
* hide the header
* being able to dynamically choose the icon (I don't want to use a fixed one for all situations)
* can have multiple notification settings (can use in different contexts)

**Comment by chrissainty** [comment]
Hi @drma-dev, could you clarify a couple of questions.

When you say you don't want to use a fixed icon, do you mean you use different a different success icon in different parts of the same application?

What do you mean by multiple notification settings in different contexts?

**Comment by chrissainty** [comment]
Cool, thanks.

So you can configure different icons for different type of alert right now. If you have a look at the [README](https://github.com/Blazored/Toast/blob/master/README.md) it explains how you can do this.

I understand what you mean now by different notification settings. That is something we can look at adding.

**Comment by drma-dev** [comment]
About the icons ... I had read, but from what I understand, you adjust the icons by type of alert. I want to be able to have different icons for the same type of alert, depending on the message I want to show.

**Comment by chrissainty** [comment]
> 
> 
> About the icons ... I had read, but from what I understand, you adjust the icons by type of alert. I want to be able to have different icons for the same type of alert, depending on the message I want to show.

Ah ok, that what I was asking in my first reply. It obviously got lost in translation :)

**Comment by drma-dev** [comment]
if you need help, just let me know

**Comment by nyash** [comment]
Hi,

I think the best general approach would be to have a ToastSettings object that globally is initialized in the markup and provides default values for all the possible options.

```
    <BlazoredToasts 
        Option1="xxx"
        Option2="yyy"
        Option3="zzz"
         ...
     />
```

Then add an overload to all the `ShowXXX` methods of IToastService that accepts a `ToastSettings` object which would allow us to override the defaults.

e.g:
_toastService.ShowInfo("added ok", new ToastSettings() {
  Option1="XXX",
  Option3="ZZZ"
});

Then the settings should be merged which would allow for unique settings on per toast call.

**Comment by nyash** [comment]
Hi,

I think the best general approach would be to have a ToastSettings object that globally is initialized and provides default values for all the possible options.

```
services.AddBlazoredToast();

/* or customize the defaults via */

services.AddBlazoredToast(conf => {
 conf.Option1="xxx",
 conf.Option2="yyy",
 conf.Option3="zzz"
 ...
 conf.Option10="qqq"
});
```

Then add an overload to all the `ShowXXX` methods of IToastService that accepts a `ToastSettings` object which would allow us to override some of the defaults.

e.g:

```
_toastService.ShowInfo("added ok", new ToastSettings() {
  Option1="XXX",
  Option3="ZZZ"
});
```

Then the settings should be merged which would allow for unique settings on per toast invocation.

**Comment by nyash** [comment]
Hi,

I think the best general approach would be to have a settings object that provides global default values for all the possible options.

```
services.AddBlazoredToast();

/* or customize the global defaults via */

services.AddBlazoredToast(conf => {
 conf.Option1="xxx",
 conf.Option2="yyy",
 conf.Option3="zzz"
 ...
 conf.Option10="qqq"
});
```

Then add an overload to all the `ShowXXX` methods of IToastService that accepts a `ToastSettings` object which would allow us to override some of the global defaults.

e.g:

```
/* override some of the global defaults, leave rest intact */
_toastService.ShowInfo("added ok", new ToastSettings() {
  Option1="XXX",
  Option3="ZZZ"
});
```

Then the actual options passed would be the result of a merge of the global settings and the toastsettings from the method call. This would allow to have custom options on per toast invocation.

**Comment by nyash** [comment]
Hi,

I think the best general approach would be to have a settings object that provides global default values for all the possible options.

```
services.AddBlazoredToast();

/* or customize the global defaults via */

services.AddBlazoredToast(conf => {
 conf.Option1="xxx",
 conf.Option2="yyy",
 conf.Option3="zzz"
 ...
 conf.Option10="qqq"
});
```

Then add an overload to all the `ShowXXX` methods of `IToastService` that accepts a `Settings` object which would allow us to override some of the global defaults.

e.g:

```
/* override some of the global defaults in the method invocation */
_toastService.ShowInfo("added ok", new Settings() {
  Option1="XXX",
  Option3="ZZZ"
});
```

Then the actual options passed would be the result of a merge of the global settings and the toastsettings from the method call. This would allow to have custom options on per toast invocation. 

I also share a similar sentiment as drma-dev that the current implementation doesn't allow for much customization on per toast basis. I think the above approach would fix it.

**Comment by nyash** [comment]
Hi,

I think the best general approach would be to have a settings object that provides global default values for all the possible options.

```
services.AddBlazoredToast();

/* or customize the global defaults via */

services.AddBlazoredToast(conf => {
 conf.Option1="xxx",
 conf.Option2="yyy",
 conf.Option3="zzz"
 ...
 conf.Option10="qqq"
});
```

Then add an overload to all the `ShowXXX` methods of `IToastService` that accepts a `Settings` object which would allow us to override any of the global defaults.

e.g:

```
/* override some of the global defaults in the method invocation */
_toastService.ShowInfo("added ok", new Settings() {
  Option1="XXX",
  Option3="ZZZ"
}); 
```

Then the actual options passed would be the result of a merge of the global settings and the toast settings from the method call. This would allow to have custom options on per toast invocation. 

Or maybe api like this (seems even easier to implement):

```
_toastService.ShowInfo("added ok", conf => {
  conf.Option1="XXX",
  conf.Option3="ZZZ"
}); 
```

Then the method would be given a copy of the global settings of which any of the options can be overriden.
 
I also share a similar sentiment as drma-dev that the current implementation doesn't allow for much customization on per toast basis. I think the above approach would fix it.

**Comment by Liero** [comment]
+1
Regarding the design, what about 
`void ShowToast(ToastLevel level, string message, string heading = "",  ToastSettings settings = null);`

**Comment by chrissainty** [comment]
This was done as part of the v4 release.
