### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by IcepiQ** [Blazored/Toast#76]
Hi,

Should the toast notification be sending over 200 Blazor requests to the server during the 5 seconds while it is open?
I can see 215 requests for the 5 seconds while the notification is open, these start as soon as it opens then stop as soon as it closes.

Thanks

**Comment by chrissainty** [comment]
Hi @IcepiQ, could you provide some more detail around where you're seeing this and what hosting model you are using?

**Comment by IcepiQ** [comment]
Hi Chris,

Thanks for the response, I've managed to work out the issue, nothing wrong with the Toast Component.
I worked out it was working fine within IIS Express but when I published it to IIS SignalR was falling back to polling and was making hundreds of polling requests.
All I had to do was install the Web Sockets protocol in IIS and now it works fine.

Thanks

**Comment by chrissainty** [comment]
Thanks for letting us know and glad you got it sorted.
