### ISSUE TITLE
[Feature Request] Toast settings should be reworked to allow greater customization

### ISSUE THREAD

**Issue by nyash** [Blazored/Toast#77]
Hi,
 
I think that the toast settings should be reworked to allow greater customization. 

There should be global and per toast settings which the latter can override. Both of which should mirror one another.

For global settings one possible option is this:

```
/* register with some global defaults */
services.AddBlazoredToast();

/* or customize the global defaults via */
services.AddBlazoredToast(conf => {
 conf.Option1="xxx",
 conf.Option2="yyy",
 conf.Option3="zzz"
 ...
 conf.Option10="qqq"
});
```

For per toast settings two possible options are:

1.
```
/* override some of the global defaults in the method invocation */
_toastService.ShowInfo("added ok", new Settings() {
  Option1="XXX",
  Option3="ZZZ"
}); 
```

Then the actual options passed would be the result of a merge of the global settings and the toast settings from the method call. 

2. 

```
/* override some of the global defaults in the method invocation */
_toastService.ShowInfo("added ok", conf => {
  conf.Option1="XXX",
  conf.Option3="ZZZ"
}); 
```

Then the method would be given a copy of the global settings via a lambda of which any of the options can be overriden.
  
&nbsp;
&nbsp;

All the current (and future) global toast settings should be made possible to be overriden on per toast basis.

I have personally wanted to customize some aspects of the toasts (on per toast basis), but with the current implementation many of the options can only be specified globally for all the toast types (same problem discussed in #75).  The above approach would nicely fix it allowing to override any of the current (and future) options on per toast basis.

**Comment by chrissainty** [comment]
I agree @nyash, adding this ability would be a big improvement. We do exactly what you've suggested for Blazored Modal and it works really well.

**Comment by chrissainty** [comment]
This was completed with the v4 release.
