### ISSUE TITLE
[Question]anchoring to the left

### ISSUE THREAD

**Issue by beardiedog** [Blazored/Toast#79]
**Please be sure to check the readme file before raising an issue.**
Hi is it possible to have the notifications anchored to the left?  I am developing for mobile and have some non responsive grids that enable the users to scroll along to read all the information but this makes the canvas off the screen and hence notifications anchored right they do not see.

**Comment by chrissainty** [comment]
Hey, as the README states, the position of the modal is configurable using the `Position` parameter.

```
<BlazoredToasts Position="ToastPosition.BottomLeft" />
```

**Comment by beardiedog** [comment]
ah great I'll take a look at that then I assumed it would be configurable like others I've tried that's great news thanks
