### ISSUE TITLE
A minor spelling error in code.

### ISSUE THREAD

**Issue by larshg** [Blazored/Toast#8]
https://github.com/Blazored/Toast/blob/744a08121204b7e44d04008b4fa33e8409b49ba9/src/Blazored.Toast/Configuration/ToastOptions.cs#L3

Tried to copy paste the guide - and it gave error due to the spelling error :)

**Comment by chrissainty** [comment]
Thanks for reporting this @larshg! 
 
No fixed and a new build should be on NuGet in the next 30 minutes.
