### ISSUE TITLE
[Bug] Toast is not displayed on page with Route parameters

### ISSUE THREAD

**Issue by otahirs** [Blazored/Toast#80]
~~When a page contains a route parameter, Toast is not injected.
In the following example, toast works fine on `/Page`, however it is not displaying on `/Page/foo`~~

~~`@page "/Page"`~~
~~`@page "/Page/{routeparameter}"`~~

~~_more on route parameters https://docs.microsoft.com/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-3.1#route-parameters_~~

**Comment by chrissainty** [comment]
HI @otahirs, could you provide some more information on what is happening? There is no way I can diagnose the issue with the current information. Ideally, you could create a simple repro of the issue, or describe the exact steps needed to recreate the problem. Thanks.

**Comment by otahirs** [comment]
I have tried to make a minimal working example page and found out, that the problem is actually not within the Parameters.

If the page is accessed via a `href`, everything works fine, but when the page is accessed by changing the Url in the adress bar, the Toast Service does not fire from the `OnInitialized` function.
```c#
@page "/Page"

@inject IToastService toastService

<h1>TestPage</h1>
<p>@Text</p>

@code {
   
    public string Text { get; set; }

    protected override void OnInitialized()
    {
       toastService.ShowInfo("Toast is here");
       Text = "OnInitialized works";
    }
}

```
![Screencast from 29 6 2020 18 32 46](https://user-images.githubusercontent.com/24588500/86032213-431a8300-ba37-11ea-9a86-7f63f950f4de.gif)

**Comment by chrissainty** [comment]
Are you seeing any errors in the console when you load the page directly?

**Comment by otahirs** [comment]
I do not. Here is the barebone project from the video.
[ToastDemo.zip](https://github.com/Blazored/Toast/files/4847606/ToastDemo.zip)

**Comment by linkdotnet** [comment]
I know I am a bit late to the party, but the "issue"  is more or less design.

If you have a page which consists out of multiple components, `OnInitialized` gets first called from the Page *then* from the `Component`. Now we have two cases:

1. You redirect from index to your test page.
2. You hit F5 as in your example

Keep in mind the BlazorToastService is registed `Scoped`:
For 1: You are still in your request, so the component is already initialized. Therefore you see a toast as the necessary properties are also initilaized. 

For 2: You make a new request: Now the order is important. First comes `Page.OnInitialized` then `Component.OnInitialized`. In this case the BlazorToastService is not properly initialized.
@chrissainty  `OnShow` is always null.

@otahirs I would suggest put it into `OnAfterRender` just to be save.
PS: Depending whether or not you have `ServerPrerendered` active, `OnInitilaized` gets called twice.

**Comment by linkdotnet** [comment]
I would suggest to close the bug as it is more related to how Blazor works in general and not how BlazorToast operates.

**Comment by chrissainty** [comment]
Hi @otahirs.

Moving the `BlazoredToasts` component to the top of the MainLayout resolves the issue. To be clear, the following works:

```razor
@inherits LayoutComponentBase

<BlazoredToasts />

<div class="sidebar">
    <NavMenu />
</div>

<div class="main">
    <div class="top-row px-4">
        <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
    </div>

    <div class="content px-4">
        @Body
    </div>
</div>
```

This doesn't:

```razor
@inherits LayoutComponentBase

<div class="sidebar">
    <NavMenu />
</div>

<div class="main">
    <div class="top-row px-4">
        <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
    </div>

    <div class="content px-4">
        @Body
    </div>
</div>

<BlazoredToasts />
```
