### ISSUE TITLE
The path must be absolute

### ISSUE THREAD

**Issue by andrepires** [Blazored/Toast#83]
Hi.
Trying Blazored on an app running in Docker (Linux) throws error as soon as I install the extension.
It's not even necessary to set it up. 
Just install it and try to run.
It throws error with message "The path must be absolute".

**Comment by chrissainty** [comment]
Hi @andrepires,

Someone has mentioned that they are seeing this behaviour with Blazored Modal as well. They linked an issue on the ASP.NET Core repo which I can't find now which implied it could be the result of an issue with Blazor itself. I'll find the original message and link and get back to you.

**Comment by andrepires** [comment]
Ok. Thank you:

**Comment by chrissainty** [comment]
Hi @andrepires, I've not had any luck tracking down the issue, are you still experiencing the problem?

**Comment by andrepires** [comment]
Hi.
When it happened and I was not able to solve the problem, I removed the
library.
I can install and try again.
I will do it and let you know.

**Comment by chrissainty** [comment]
I'm going to close this due to a lack of information. If more information can be provided then this issue can be reopened.
