### ISSUE TITLE
Toast is not loading properly the first time

### ISSUE THREAD

**Issue by Rymix** [Blazored/Toast#85]
Hi,

I'm running blazor webassembly 3.2.0 and toast 3.1.2.
But i have some issue, the first time i run my blazor application, there is an issue with the toast.
If i refresh the page, it will working fine.

![image](https://user-images.githubusercontent.com/7524521/87766386-0c74a300-c854-11ea-964b-62e359d01d5d.png)

This is at the left top corner instead of the right top corner and red toast.

Thank you for your help !

**Comment by chrissainty** [comment]
Hi @Rymix, this looks like a potential caching issue or some other local browser problem. We see these from time to time. If you could clear your browser cache, then try again. Also try and open the page in a private/incognito window.

**Comment by grserwe** [comment]
Rymix, did you get this working?  I tried Chris's suggestion of private/incognito window and still get 404 error trying to get either the minified or non minified stylesheet.  If I manually add a copy of the stylesheet the toasts work just fine.   Obviously not a long term solution, but I'll try and do some digging.  I'm also using webassembly 3.2.0.

**Comment by grserwe** [comment]
I updated my .net sdk and now it finds the css file.  Very strange.

**Comment by Rymix** [comment]
Dear @chrissainty
Yes it was cache issue, everything is working great now !
Thank you for your help !
