### ISSUE TITLE
Timeout takes longer than expected

### ISSUE THREAD

**Issue by pablopioli** [Blazored/Toast#86]
**Describe the bug**
If you set the timeout the amount of time it takes for the toast to dissappear is always longer than expected.

**To Reproduce**
In the WebAssembly sample set a timeout of 2 seconds, you will see the toast takes much longer to dissappear. In my machine it takes around 5 seconds.

**Suggestion**
The resolution timer en Blazor (specially in WebAssembly) is not granular enough to handle such short times.

In this Gist
https://gist.github.com/pablopioli/f7da61e490c575a306501067bfd0fca1

I propose an non breaking improvement that can alleviate this problem.

**Comment by chrissainty** [comment]
Thanks @pablopioli, I'll add this in the next release.

**Comment by chrissainty** [comment]
@pablopioli I've just tried this out using the sample projects and changing the timeout reflects correctly as far as I can see. Can you provide any more info around this?

**Comment by pablopioli** [comment]
You should try it in Firefox. See an example in https://youtu.be/mQWLB_4-h1A

My **guess** is that recreating the timer can lead to threading problems, where the browser does not reschedule the timer until some time later. So I opted to use an interval and preserve the original timer.

**Comment by chrissainty** [comment]
Thanks for that @pablopioli. I've made some updates to the timer based on your gist, keeping the single timer instance. It's much cleaner and more efficient.
