### ISSUE TITLE
[Feature Request] Make the behaviour of the heading setting more predictable

### ISSUE THREAD

**Issue by blacksmith01** [Blazored/Toast#94]
Is there any way I can use it as below?

![Toastify](https://user-images.githubusercontent.com/567946/96800892-68e1f280-1441-11eb-9a0e-338f7224151b.png)

**Comment by blacksmith01** [comment]
Oh, I find a way.
I can use heading parameter for message.
like `ShowSuccess("","This is a toast")`

**Comment by esso23** [comment]
Requesting reopen:
First parameter of ShowSuccess is message and second is heading (with a default value of "").
If I request a heading with value "", I should get a heading with value "" (empty), not a heading with value "INFO".

I would propose setting default value of heading to "INFO" - as is displayed. Setting null should hide the heading. This would be much clearer than the current solution.

**Comment by BewaControl-ReneDivossen** [comment]
null and string.Empty should both make heading dissappear (and no empty space should be taken for the nonexisting header)

**Comment by blacksmith01** [comment]
I agree with eso23's suggestion.
I was expecting that at first, too.
It will be nice if Chris update it.

**Comment by Rowingwolf** [comment]
I agree.  Would like to suppress the heading, especially for info toasts.

**Comment by ltemimi** [comment]
has this been done I do not want a capital header

**Comment by chrissainty** [comment]
Closing as headings are being removed from the default toasts in the next release (see #170)
